### ISSUE TITLE
Documentation note on imports

### ISSUE THREAD

**Issue by HuntBurdick** [cbothner/react-activestorage-provider#20]
Is it worth noting that DirectUploadProvider is not a default export and needs to be called like:

`import { DirectUploadProvider } from 'react-activestorage-provider'`

While the default ActiveStorageProvider is imported like so:

`import ActiveStorageProvider from 'react-activestorage-provider'`

This tripped me up for a second until I looked through the code. May not be obvious to a new developer.

**Comment by cbothner** [comment]
Thanks for the issue! This was an oversight that I’m glad to remediate 👍
