### ISSUE TITLE
'uploads' render prop after all uploads have finished

### ISSUE THREAD

**Issue by CaptainLexington** [cbothner/react-activestorage-provider#24]
When all uploads have finished, it seems that `ActiveStorageProvider`'s child is called again with the `uploads` render prop set to the empty list - which means our final 'finished' message is displayed for only a split second before disappearing entirely. Is this the intended behavior? Do have any suggestions for displaying a persistent success message when the uploads have finished? My first thought was to use `redux` or component state, but neither of these are supposed to be updated from the render function of a component. Thoughts?

**Comment by cbothner** [comment]
Hi! Good question. What you've described is the intended behavior, I think. But you're right that the render props aren't super useful as a persistent overall success message. If you're allowing multiple uploads it's good for showing which files have already finished, but to notify the user about the overall success of an upload I imagine the `onSubmit` prop will be more useful. In your `onSubmit` function, you could set redux or component state to display the file the user just uploaded or trigger an alert/toast/flag, for example.

But let me know if I'm misunderstanding and that isn't sufficient for your needs!

**Comment by adenta** [comment]
@CaptainLexington How did you manage to solve your problems?

Personally, I'm using the `<DirectUploadsProvider/>`, so there dosen't really seem to be any good way of persisting that success message.

Edit cbothener/captianLexington/s

**Comment by CaptainLexington** [comment]
Unfortunately I don't remember, @adenta , and I no longer have access to this code!
