### ISSUE TITLE
Allow Modification of body Sent to Endpoint

### ISSUE THREAD

**Issue by jdalt** [cbothner/react-activestorage-provider#26]
When using this library to create a new object with an attachment, it's not possible to use the `ActiveStorageProvider` to send other attributes on the model. The body is fixed in the form
```
{
  [model.toLowerCase()]: {
    [attribute]: multiple ? signedIds : signedIds[0],
  }
}
```

This makes creating new objects that have other required fields impossible. I think it would be useful for the component implementor to define a function to build the body in any way they see fit. This will also make the library more flexible for apis that don't conform to the current body building structure.

I've built a PR that demonstrates how I think this should be done:
https://github.com/cbothner/react-activestorage-provider/pull/25

**Comment by cbothner** [comment]
Resolved. See https://github.com/cbothner/react-activestorage-provider/pull/25#issuecomment-472106522
