### ISSUE TITLE
url not defined

### ISSUE THREAD

**Issue by jshum** [cbothner/react-activestorage-provider#27]
Thanks for the great work @cbothner 

I just wanted to open an issue here for others to see in the future. It's actually not a bug of the library, but just in case someone else also runs into this since it took me a long time to figure out

If you see the following exception

```
index.js:3034 Uncaught TypeError: Cannot read property 'url' of undefined
    at new t (index.es.js:1121)
    at t.eval [as callback] (index.es.js:1121)
    at t.value (index.es.js:1121)
    at XMLHttpRequest.eval (index.es.js:1121)
    at XMLHttpRequest.wrapped (index.js:3010)
```

The code that is throwing the error is from the [active-storage javascript code](https://github.com/rails/rails/tree/5-2-stable/activestorage/app/javascript/activestorage). The error message is cryptic, but actually what's happening is that the javascript code is not finding the needed attributes from the response JSON of the `/direct_uploads` API call. The javascript code expects `snake_case` by default, so be sure to check you are not using camelCase on your keys (as I was) or overriding key names in your controller code.

Thanks!

**Comment by cbothner** [comment]
Thanks for teaching forward!
