### ISSUE TITLE
Usage with React Native and Apollo?

### ISSUE THREAD

**Issue by Jarred-Sumner** [cbothner/react-activestorage-provider#3]
How tricky would it be to get this working with React Native and Apollo?

**Comment by cbothner** [comment]
This package depends on the `activestorage` package distributed with Rails, which to my knowledge uses DOM APIs and does not support React Native. For now, I’m sorry to say that React Native support is out of scope for this package.

**Comment by cbothner** [comment]
In case it’s helpful, I ended up writing up a bit of how-to that details the requests that go into uploading a file to a model using activestorage. I haven’t figured out a react native compatible way of making an MD5 checksum of the file, which is necessary for a direct upload, but maybe this will provide some direction. https://github.com/rails/rails/issues/32208#issuecomment-383737803
