### ISSUE TITLE
React:ServerRendering::PrerenderError

### ISSUE THREAD

**Issue by mapinetree311** [cbothner/react-activestorage-provider#34]
Hi.
How are you doing?
My project is built with Ruby on Rails for back-end and React for front-end.
React-Rails gem was used.
When I import ReactActiveStorageProvider in the react, it causes React::ServerRendering::PrerenderError.

![Screenshot 2019-04-05 07 47 16](https://user-images.githubusercontent.com/22128210/55636361-ed95ee80-577f-11e9-83ff-6c253ec25de3.png)

I only imported this package and got this issue.
What's wrong?

**Comment by mapinetree311** [comment]
It was resolved my myself.
I didn't add this props.
`prerender: false`

**Comment by danielyaa5** [comment]
this should be reopened, the problem was never solved.
