### ISSUE TITLE
Resize image before upload

### ISSUE THREAD

**Issue by HuntBurdick** [cbothner/react-activestorage-provider#35]
Just starting to tackle this and was curious if anyone had a working example. I'd like to resize/compress images before transmitting them over the wire. I'm looking at the html image API and canvas to accomplish this. Thoughts?

I'll post what I come up with after I get it all sorted out.

**Comment by ahharvey** [comment]
@HuntBurdick did you ever find a solution to this? I'm looking at the `onBeforeBlobRequest` to perform something similar, but have not been able to figure out a working implementation.

**Comment by HuntBurdick** [comment]
@ahharvey I'm sorry; I abandoned the approach for now and haven't looked at the issue in a while.
